name: wasmedge-sys-docs

concurrency:
  group: rust-crate-release-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "rust/[0-9]+.[0-9]+.[0-9]+*"

# env:
#   CARGO_INCREMENTAL: 0
#   CARGO_NET_RETRY: 10
#   RUSTFLAGS: "-D warnings -W unreachable-pub"
#   RUSTUP_MAX_RETRIES: 10

jobs:
  rustdoc:
    name: rustdoc
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          with: 
            fetch-depth: 0

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
            

      - name: Build Documentation
        run: |
          cd bindings/rust/wasmedge-sys
          cargo doc --all --no-deps --target-dir=./target

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: bindings/rust/wasmedge-sys/target/doc
          force_orphan: true
